repos:
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.23
  hooks:
  - id: validate-pyproject
    additional_dependencies: ["validate-pyproject-schema-store[all]"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.2
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format