repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.22
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml
        description: Validate pyproject.toml files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff
        description: Run ruff linter
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff format
        description: Run ruff formatter
  # - repo: local
  #   hooks:
  #     - id: clang-tidy
  #       name: clang-tidy
  #       entry: bash
  #       language: system
  #       files: ^(src|include)/.*\.(cpp|hpp|cc|h)$
  #       args: [-c, 'if [ $# -gt 0 ]; then clang-tidy --format-style=none "$@" -- -std=c++20 -I./include -I./src -I./external/madrona/include; fi', --]
  #       exclude: ^(external|tests)/