repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.22
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml
        description: Validate pyproject.toml files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff
        description: Run ruff linter
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^madrona_escape_room/generated_.*\.py$
      - id: ruff-format
        name: ruff format
        description: Run ruff formatter
        exclude: ^madrona_escape_room/generated_.*\.py$
