[build-system]
requires = []
build-backend = "madrona_py_build"
backend-path = ["external/madrona/py"]

[project]
name = "madrona_escape_room"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.20.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-xdist>=3.0.0",  # For parallel test execution
]

[tool.madrona.packages.madrona_escape_room]
ext-only = true
ext-out-dir = "build"

# This module includes the PPO implementation for the training demo
[tool.madrona.packages.madrona_escape_room_learn]
path = "train_src/madrona_escape_room_learn"

[tool.pytest.ini_options]
testpaths = ["tests/python"]
norecursedirs = ["external", "build", ".venv", "*.egg", "dist"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
