[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "madrona-escape-room"
version = "0.1.1"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.20.0",
    "torchrl>=0.2.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-xdist>=3.0.0",  # For parallel test execution
]

# Removed madrona-specific configuration
# The package is now built using standard setuptools

[tool.pytest.ini_options]
testpaths = ["tests/python"]
norecursedirs = ["external", "build", ".venv", "*.egg", "dist"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
