program: scripts/train.py
project: madrona-escape-room
command:
  - uv
  - run
  - python
  - ${program}
  - "--clip-value-loss"
  - "--fp16"
  - "--gpu-sim"
  - "--gpu-id"
  - "0"
  - "--level-file"
  - "levels/obstacle_course_20x48.lvl"
  - ${args}
method: bayes
metric:
  name: episodes/reward_ema
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 50
parameters:
  # Core training parameters (fixed for efficiency)
  num-worlds:
    value: 4096
  num-updates:
    value: 4000
  steps-per-update:
    value: 40
  num-bptt-chunks:
    value: 8
  
  # Key hyperparameters to optimize
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.001
  gamma:
    values: [0.995, 0.998]
  
  # PPO tuning (most impactful)
  entropy-loss-coef:
    values: [0.005, 0.01, 0.02]
  
  # Fixed parameters
  value-loss-coef:
    value: 0.5
  num-channels:
    value: 256
  
  # Random seed for reproducibility
  seed:
    values: [0, 42, 123, 456, 789]